Accounting/Controllers/Common/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repository;
using Repository.Common;
using Repository.UnitOfWork;


namespace Accounting.Controllers.Common
{
    public class CommonController : BaseController
    {
        public CommonController(IUnitOfWork uow)
        {
           Uow = uow;
        }
       
        #region for Bank

        public ActionResult Bank()
        {
            IEnumerable<CompanyInfo> listcompany = Uow.CompanyInfoRepository.GetAll();
            var SelectCopmpanyList = new SelectList(listcompany, "CompanyID", "CompanyName", "");
            ViewData["VdCompanyList"] = SelectCopmpanyList;
            return View();
        }
        
        public void Bankadd(Bank bank)
        {
            bank.Creator = Session["UserID"].ToString();
            bank.CreationDate = System.DateTime.Now;
            bank.Modifier = "Rezaul";
            bank.ModificationDate = System.DateTime.Now;

           Uow.BankRepository.Add(bank);
        }
        public void Bankupdate(Bank bank)
        {
            bank.Creator = Session["UserID"].ToString();
            bank.CreationDate = System.DateTime.Now;
            bank.Modifier = Session["UserID"].ToString();
            bank.ModificationDate = System.DateTime.Now;
            Uow.BankRepository.Update(bank);
        }

        public void Bankdelete(int BankID)
        {
            Uow.BankRepository.Delete(BankID);
        }

        public JsonResult GetAllBank()
        {
            IEnumerable<Bank> listBank = Uow.BankRepository.GetAll();
            return Json(listBank);
        }
        public JsonResult GetBankByID(int BankID)
        {
            Bank bank = Uow.BankRepository.GetById(BankID);
            return Json(bank);
        }
        
        public JsonResult BankDetails(string sidx, string sord, int page, int rows, string filter)
        {
            IEnumerable<Bank> listBank = Uow.BankRepository.GetAll();

            int pageIndex = (page - 1);
            int pagesize = rows;
            int totalrecords = listBank.Count();
            int totalPages = totalrecords / pagesize + 1;
            var Bu = listBank.AsQueryable()
               .Skip(pageIndex * pagesize)
               .Take(pagesize)
               .OrderBy(B => B.BankID);

            string sort = string.Empty;
            var json = Json(new
            {
                total = totalPages,
                page = page,
                records = totalrecords,
                rows = (from B in Bu
                        select new
                        {
                            id = B.BankID,
                            cell = new object[]
                           {   
                               B.BankID,
                               B.CompanyID,
                               B.BankName,
                               B.Note
                           }
                        }).ToArray()
            }, JsonRequestBehavior.AllowGet);
            return json;
        }

        #endregion For Bank

        #region Branch start

        public ActionResult Branch()
        {
            IEnumerable<CompanyInfo> listcompany = Uow.CompanyInfoRepository.GetAll();
            var SelectCopmpanyList = new SelectList(listcompany, "CompanyID", "CompanyName", "");
            ViewData["VdCompanyList"] = SelectCopmpanyList;

            IEnumerable<Bank> listBank = Uow.BankRepository.GetAll();
            var SelectBankList = new SelectList(listBank, "BankID", "BankName", "");
            ViewData["VdBankList"] = SelectBankList;

            return View();
        }

        public void AddBranch(Branch branch)
        {
            branch.Creator = Session["UserID"].ToString();
            branch.CreationDate = System.DateTime.Now;
            branch.Modifier = "Rezaul";
            branch.ModificationDate = System.DateTime.Now;
            Uow.BranchRepository.Add(branch);
        }
        public void UpdateBranch(Branch branch)
        {
            branch.Creator = Session["UserID"].ToString();
            branch.CreationDate = System.DateTime.Now;
            branch.Modifier = Session["UserID"].ToString();
            branch.ModificationDate = System.DateTime.Now;
            Uow.BranchRepository.Update(branch);
        }
        public void DelectBranch(int BranchID)
        {
            Uow.BranchRepository.Delete(BranchID);
        }
        public JsonResult GetAllBranch()
        {
            IEnumerable<Branch> listBranch = Uow.BranchRepository.GetAll();
            return Json(listBranch);
        }
        public JsonResult GetBranchByID(int BranchID)
        {
            Branch objBranch = Uow.BranchRepository.GetById(BranchID);
            return Json(objBranch);
        }

        public JsonResult BranchDetails(string sidx, string sord, int page, int rows, string filter)
        {
            IEnumerable<Branch> listBranch = Uow.BranchRepository.GetAll();

            int pageIndex = (page - 1);
            int pagesize = rows;
            int totalrecords = listBranch.Count();
            int totalPages = totalrecords / pagesize + 1;
            var pu = listBranch.AsQueryable()
               .Skip(pageIndex * pagesize)
               .Take(pagesize)
               .OrderBy(p => p.BranchID);

            string sort = string.Empty;
            var json = Json(new
            {
                total = totalPages,
                page = page,
                records = totalrecords,
                rows = (from p in pu
                        select new
                        {
                            id = p.BranchID,
                            cell = new object[]
                           {   
                               p.BranchID,
                               p.CompanyID,
                               p.BankID,
                               p.BranchName,
                               p.Address,
                               p.Phone,
                               p.Mobile,
                               p.Email,
                               p.Note
                           }
                        }).ToArray()
            }, JsonRequestBehavior.AllowGet);
            return json;
        }


        #endregion

        #region CompanyInfo start

        public ActionResult Companyinfo()
        {
            IEnumerable<DistrictInfo> listDistrict = Uow.DistrictInfoRepository.GetAll();
            var SelectDistrictList = new SelectList(listDistrict, "DistrictID", "DistrictName", "");
            ViewData["VdDistrictList"] = SelectDistrictList;

            IEnumerable<CountryInfo> listCountry = Uow.CountryInfoRepository.GetAll();
            var SelectCountryList = new SelectList(listCountry, "CountryID", "CountryName", "");
            ViewData["VdCountryList"] = SelectCountryList;
           
            return View();
        }

        public void comAdd(CompanyInfo companyInfo)
        {
            companyInfo.IssueDate = System.DateTime.Now;
            companyInfo.Status = true;
            companyInfo.Creator = Session["UserID"].ToString();
            companyInfo.CreationDate = System.DateTime.Now;
            companyInfo.Modifier = "Rezaul";
            companyInfo.ModificationDate = System.DateTime.Now;
            Uow.CompanyInfoRepository.Add(companyInfo);
        }

        public void comUpdate(CompanyInfo companyInfo)
        {
            companyInfo.IssueDate = System.DateTime.Now;
            companyInfo.Status = true;
            companyInfo.Creator = Session["UserID"].ToString();
            companyInfo.CreationDate = System.DateTime.Now;
            companyInfo.Modifier = Session["UserID"].ToString();
            companyInfo.ModificationDate = System.DateTime.Now;
            Uow.CompanyInfoRepository.Update(companyInfo);

        }
        public void comDelete(int CompanyID)
        {
            Uow.CompanyInfoRepository.Delete(CompanyID);
        }
        public JsonResult GetAllCompanyInfo()
        {
            IEnumerable<CompanyInfo> listCompanyInfo = Uow.CompanyInfoRepository.GetAll();
            return Json(listCompanyInfo);
        }
        public JsonResult GetCompanyInfoByID(int CompanyID)
        {
            CompanyInfo obCompanyInfo = Uow.CompanyInfoRepository.GetById(CompanyID);
            return Json(obCompanyInfo);
        }

        public JsonResult CompanyInfoDetails(string sidx, string sord, int page, int rows, string filter)
        {
            IEnumerable<CompanyInfo> listCompanyInfo = Uow.CompanyInfoRepository.GetAll();

            int pageIndex = (page - 1);
            int pagesize = rows;
            int totalrecords = listCompanyInfo.Count();
            int totalPages = totalrecords / pagesize + 1;
            var pu = listCompanyInfo.AsQueryable()
               .Skip(pageIndex * pagesize)
               .Take(pagesize)
               .OrderBy(p => p.CompanyID);

            string sort = string.Empty;
            var json = Json(new
            {
                total = totalPages,
                page = page,
                records = totalrecords,
                rows = (from p in pu
                        select new
                        {
                            id = p.CompanyID,
                            cell = new object[]
                           {   
                               p.CompanyID,
                               p.CompanyName,
                                p.Address,
                                 p.DistrictID,
                                  p.PostCode,
                                   p.CountryID,
                                   p.VATRegNo,
                                    p.Phone,
                                     p.Mobile,
                                      p.Fax,
                                      p.eMail,
                                      p.Note
                                     

Accounting/Views/Shared/AdminMenu.cshtml
<ul class="pureCssMenu pureCssMenum pureBottomBorder">
    
    <li class="pureCssMenui0">
        <a class="pureCssMenui0" href="#">
            <span class="members_menu_icon">POS</span><![if gt IE 6]>
        </a><![endif]><!--[if lte IE 6]><table><tr><td><![endif]-->
        <ul class="pureCssMenum">          
            <li class="pureCssMenui">@Html.ActionLink("Product Info", "ProductInfo", "POS_Setup")</li>
            <li class="pureCssMenui">@Html.ActionLink("Brand", "Brand", "POS_Setup")</li>
            <li class="pureCssMenui">@Html.ActionLink("Payment Type", "PaymentType", "Accounting_Financial")</li>   
            <li class="pureCssMenui">@Html.ActionLink("Product Category", "ProductCategory", "POS_Setup")</li>         
            <li class="pureCssMenui">@Html.ActionLink("Customer Info", "CustomerInfo", "POS_Setup")</li>         
            <li class="pureCssMenui">@Html.ActionLink("Supplier Info", "SupplierInfo", "POS_Setup")</li>
        
        </ul>
        <!--[if lte IE 6]></td></tr></table></a><![endif]-->
    </li>
    <li class="pureCssMenui0">
        <a class="pureCssMenui0" href="#">
            <span class="members_menu_icon">Set Up</span><![if gt IE 6]>
        </a><![endif]><!--[if lte IE 6]><table><tr><td><![endif]-->
        <ul class="pureCssMenum">
            <li class="pureCssMenui">@Html.ActionLink("Company Info", "Companyinfo", "Common")</li>        
          
            <li class="pureCssMenui">@Html.ActionLink("Bank", "Bank", "Common")</li>
            <li class="pureCssMenui">@Html.ActionLink("Branch", "Branch", "Common")</li>            
            <li class="pureCssMenui">@Html.ActionLink("Country", "CountryInfo", "Common")</li>
            <li class="pureCssMenui">@Html.ActionLink("District", "District", "Common")</li>                       
        </ul>
        <!--[if lte IE 6]></td></tr></table></a><![endif]-->
    </li>
    

    <li class="pureCssMenui0">
        <a class="pureCssMenui0" href="#">
            <span class="members_menu_icon">Purchase</span><![if gt IE 6]>
        </a><![endif]><!--[if lte IE 6]><table><tr><td><![endif]-->
        <ul class="pureCssMenum">
            <li class="pureCssMenui">@Html.ActionLink("Purchase", "PurchaseItem", "POS_Purchase")</li>
            <li class="pureCssMenui">@Html.ActionLink("Purchase Return", "PurchaseReturn", "POS_Purchase")</li>
            <li class="pureCssMenui">@Html.ActionLink("Sales", "SalesItem", "POS_Sales")</li> 
            <li class="pureCssMenui">@Html.ActionLink("Sales Return", "SalesReturn", "POS_Sales")</li>          
        </ul>
        <!--[if lte IE 6]></td></tr></table></a><![endif]-->
    </li>
     <li class="pureCssMenui0">
        <a class="pureCssMenui0" href="#">
            <span class="members_menu_icon">Reports</span><![if gt IE 6]>
        </a><![endif]><!--[if lte IE 6]><table><tr><td><![endif]-->
        <ul class="pureCssMenum">
                                                
        </ul>
        <!--[if lte IE 6]></td></tr></table></a><![endif]-->
    </li>
</ul>

Accounting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Shop Management System</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.20.min.js"></script>

</head>
<body>
    @* <header>
        <div style="height: 75px; background-color: #000000;">
        </div>
        <div style="height: 25px; background-color: #D3D3D3;">
        </div>
    </header>
    <div id="body">
        <div style="width: 100%">
            <div style="min-height: 40%; float: left; width: 20.5%; padding-left: 5px; padding-top: 2px; padding-bottom: 10px;">
                @Html.Partial("AdminMenu")
            </div>

            <div style="min-height: 40%; border-left: 1px solid #206C9F; width: 77.5%; float: left; padding-left: 10px; padding-top: 2px; padding-bottom: 10px;">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - DSL Accounting Information System</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)*@


    <div id="container">
        <div id="banner">
            <div style="float: left; padding: 2px;">
                @*<img src="images/bond.png" />*@
            </div>
            <div style="float: left;">
                @*<img src="images/software-name.png" />*@
            </div>
        </div>
        <div id="navcontainer">
            <ul id="navlist">
                <li><b>User Code :</b></li>
                <li><b>Designation :</b></li>
            </ul>
            <span style="float: right"></span>
        </div>
        <div id="sidebar">
            @Html.Partial("AdminMenu")
        </div>
        <div id="content">
            @RenderBody()
        </div>
        <div id="footer">
            <div align="center">
                <div>Deloved by Rezaul Islam</div>
                <div>
                    This System is designed and developed by Rezaul Islam <a
                        href="#" target="_blank"><strong>(LUT)</strong></a>
                </div>
            </div>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </div>



</body>
</html>