Accounting/Controllers/POS/Setup/POS_SetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repository;
using Repository.Common;
using Repository.UnitOfWork;

namespace Accounting.Controllers.POS.Setup
{
    public class POS_SetupController : BaseController
    {
        public POS_SetupController(IUnitOfWork uow)
        {
           Uow = uow;
        }

        #region Customerinfo

        public ActionResult CustomerInfo()
        {
            IEnumerable<DistrictInfo> listDistrict = Uow.DistrictInfoRepository.GetAll();
            var SelectDistrictList = new SelectList(listDistrict, "DistrictID", "DistrictName", "");
            ViewData["VdDistrictList"] = SelectDistrictList;

            IEnumerable<CountryInfo> listCountry = Uow.CountryInfoRepository.GetAll();
            var SelectCountryList = new SelectList(listCountry, "CountryID", "CountryName", "");
            ViewData["VdCountryList"] = SelectCountryList;

            return View();
        }

        public void CusAdd(CustomerInfo Customer)
        {
            Customer.Status = true;
            Customer.Creator = "Rezaul";
            Customer.CreationDate = System.DateTime.Now;
            Customer.Modifier = "Rezaul";
            Customer.ModificationDate = System.DateTime.Now;
            Uow.CustomerInfoRepository.Add(Customer);
        }
        public void CusUpdate(CustomerInfo Customer)
        {
            Customer.Status = true;
            Customer.Creator = "Rezaul";
            Customer.CreationDate = System.DateTime.Now;
            Customer.Modifier = "Rezaul";
            Customer.ModificationDate = System.DateTime.Now;
            Uow.CustomerInfoRepository.Update(Customer);
        }
        public void CusDelete(int CustomerID)
        {
            Uow.CustomerInfoRepository.Delete(CustomerID);
        }

        public JsonResult GetAllCustomer()
        {
            IEnumerable<CustomerInfo> listCustomerInfo = Uow.CustomerInfoRepository.GetAll();
            return Json(listCustomerInfo);
        }

        public JsonResult GetCustomerInfoByID(int CustomerID)
        {
            CustomerInfo info = Uow.CustomerInfoRepository.GetById(CustomerID);
            return Json(info);
        }

        public JsonResult CustomerInfoDetails(string sidx, string sord, int page, int rows, string filter)
        {
            IEnumerable<CustomerInfo> listCustomerInfo = Uow.CustomerInfoRepository.GetAll();

            int pageIndex = (page - 1);
            int pagesize = rows;
            int totalrecords = listCustomerInfo.Count();
            int totalPages = totalrecords / pagesize + 1;
            var Cu = listCustomerInfo.AsQueryable()
               .Skip(pageIndex * pagesize)
               .Take(pagesize)
               .OrderBy(C => C.CustomerID);

            string sort = string.Empty;
            var json = Json(new
            {
                total = totalPages,
                page = page,
                records = totalrecords,
                rows = (from C in Cu
                        select new
                        {
                            id = C.CustomerID,
                            cell = new object[]
                           {   C.CustomerID,
                               C.CustomerCode,
                               C.CustomerName,
                               C.CustomerType,
                               C.Propietor,
                               C.ContactPerson,
                               C.Address,
                               C.DistrictID,
                               C.CountryID,
                               C.Phone,
                               C.Mobile,
                               C.eMail,
                               C.VATRegNo,
                               C.DiscountPercent,
                               C.DistributorPoint
                              
                        }
                        }).ToArray()
            }, JsonRequestBehavior.AllowGet);
            return json;
        }
        
        #endregion

        #region ProductCategory start

        public ActionResult ProductCategory()
        {
            return View();
        }
        public void addProductCategory(ProductCategory productcategory)
        {

            productcategory.Creator = "Rezaul";
            productcategory.CreationDate = System.DateTime.Now;
            productcategory.Modifier = "Rezaul";
            productcategory.ModificationDate = System.DateTime.Now;
            Uow.ProductCategoryRepository.Add(productcategory);
        }
        public void updateProductCategory(ProductCategory productcategory)
        {
            productcategory.Creator = "Rezaul";
            productcategory.CreationDate = System.DateTime.Now;
            productcategory.Modifier = "Rezaul";
            productcategory.ModificationDate = System.DateTime.Now;
            Uow.ProductCategoryRepository.Update(productcategory);
        }
        public void deleteProductCategory(int ProductCategoryID)
        {
            Uow.ProductCategoryRepository.Delete(ProductCategoryID);
        }
        public JsonResult GetAllProductCategory()
        {
            IEnumerable<ProductCategory> listProductCategory = Uow.ProductCategoryRepository.GetAll();
            return Json(listProductCategory);
        }
        public JsonResult GetProductCategoryByID(int ProductCategoryID)
        {
            ProductCategory objProductCategory = Uow.ProductCategoryRepository.GetById(ProductCategoryID);
            return Json(objProductCategory);
        }

        public JsonResult ProductCategoryDetails(string sidx, string sord, int page, int rows, string filter)
        {
            IEnumerable<ProductCategory> listProductCategory = Uow.ProductCategoryRepository.GetAll();

            int pageIndex = (page - 1);
            int pagesize = rows;
            int totalrecords = listProductCategory.Count();
            int totalPages = totalrecords / pagesize + 1;
            var pu = listProductCategory.AsQueryable()
               .Skip(pageIndex * pagesize)
               .Take(pagesize)
               .OrderBy(p => p.ProductCategoryID);

            string sort = string.Empty;
            var json = Json(new
            {
                total = totalPages,
                page = page,
                records = totalrecords,
                rows = (from p in pu
                        select new
                        {
                            id = p.ProductCategoryID,
                            cell = new object[]
                           {   
                               p.ProductCategoryID,
                               p.ProductCategory1
                               
                           }
                        }).ToArray()
            }, JsonRequestBehavior.AllowGet);
            return json;
        }

        #endregion  ProductCategory  end

        #region ProductInfo start
        
        public ActionResult ProductInfo()
        {
            IEnumerable<ProductCategory> listProductCategory = Uow.ProductCategoryRepository.GetAll();
            var SelectProductCategoryList = new SelectList(listProductCategory, "ProductCategoryID", "ProductCategory1", "");
            ViewData["VdProductCategoryList"] = SelectProductCategoryList;

            IEnumerable<InvBrand> listInvBrand = Uow.InvBrandRepository.GetAll();
            var SelectInvBrandList = new SelectList(listInvBrand, "BrandID", "BrandName", "");
            ViewData["VdBrandList"] = SelectInvBrandList;

            IEnumerable<Inv_ColorInfo> listInvColor = Uow.ColorInfoRepository.GetAll();
            var SelectInvColorList = new SelectList(listInvColor, "ColorID", "ColorName", "");
            ViewData["VdColorList"] = SelectInvColorList;

            IEnumerable<Inv_SizeInfo> listInvSize = Uow.SizeInfoRepository.GetAll();
            var SelectInvSizeList = new SelectList(listInvSize, "SizeID", "SizeName", "");
            ViewData["VdSizeList"] = SelectInvSizeList;

            IEnumerable<TarrifType> listTarrifType = Uow.TarrifTypeRepository.GetAll();
            var SelectTarrifTypeList = new SelectList(listTarrifType, "TarrifTypeID", "TarrifType1", "");
            ViewData["VdTarrifTypeList"] = SelectTarrifTypeList;

            IEnumerable<Unit> listUnit = Uow.UnitRepository.GetAll();
            var SelectUnitList = new SelectList(listUnit, "UnitID", "UnitName", "");
            ViewData["VdUnitList"] = SelectUnitList;

            IEnumerable<VATType> listVATType = Uow.VATTypeRepository.GetAll();
            var SelectVATTypeList = new SelectList(listVATType, "VATTypeID", "VATType1", "");
            ViewData["VdVAtList"] = SelectVATTypeList;
            return View();
        }

        [HttpPost]
        public WrappedJsonResult UploadImage(ProductInfo productinfo)
        {
            //http://20fingers2brains.blogspot.com/2013/07/upload-images-to-database-in-mvc3-razor.html
            //if (ModelState.IsValid)
            //{
                Gallary gallary = new Gallary();
                productinfo.Creator = "Rezaul";
                productinfo.CreationDate = System.DateTime.Now;
                productinfo.Modifier = "Rezaul";
                productinfo.EffectiveDate = System.DateTime.Now;
                productinfo.ModificationDate = System.DateTime.Now;
                productinfo.Status = true;
                gallary.SavePlayerImage(productinfo);
                //return RedirectToAction("GetImages", new { album = imageViewModel.AlbumName.ToString() });
                
            return new WrappedJsonResult
                {
                    Data = new
                    {
                        IsValid = true,
                        Message = string.Empty,
                        ImagePath = Url.Content(String.Format("~/import/{0}", ""))
                    }
                };
            //}
            //else
            //{

Accounting/Views/POS_Setup/Brand.cshtml
@model Repository.InvBrand
@{
    ViewBag.Title = "Brand";
}

<script src="~/Scripts/ApplicationJS/Pos_Setup/Brand.js"></script>

@using (@Html.BeginForm())
{
    <div class="FormName">Brand</div>
    <div class="MainDiv">
        <div class="LeftPart">
            @Html.HiddenFor(m => m.BrandID)
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.BrandName, "Brand Name")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.BrandName, new { @class = "required" })
                </div>
            </div>
            <div class="CustombuttonOnePart">
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Save" id="btnSave" />
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Update" id="btnUpdate" />
            </div>
            <div>
                <table id="tblInvBrand"></table>
                <div id="InvBrandPager"></div>
            </div>
        </div>
    </div>
}

Accounting/Views/POS_Setup/CustomerInfo.cshtml
@model Repository.CustomerInfo
@{
    ViewBag.Title = "Customer Information";
}

<script src="~/Scripts/ApplicationJS/Pos_Setup/CustomarInfo.js"></script>

@using (@Html.BeginForm())
{
    <div class="FormName">Customer Information</div>
    <div class="MainDiv">
        <div class="LeftPart">
            @Html.HiddenFor(m => m.CustomerID)
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.CustomerCode, "Customer Code")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.CustomerCode, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.CustomerName, "Customer Name")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.CustomerName, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.CustomerType, "Customer Type")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.CustomerType, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.Propietor)
                </div>
                <div>
                    @Html.TextBoxFor(m => m.Propietor, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ContactPerson, "Contact Person")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ContactPerson, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.Address)
                </div>
                <div>
                    @Html.TextBoxFor(m => m.Address, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.DistrictID, "City")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.DistrictID, (SelectList)ViewData["VdDistrictList"], "-------Choose City-------")
                </div>
            </div>


            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.CountryID, "Country Name")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.CountryID, (SelectList)ViewData["VdCountryList"], "---ChooseCountry---")
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.Phone, "Phone No:")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.Phone, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">

                    @Html.LabelFor(m => m.Mobile, "Mobile No:")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.Mobile, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.eMail, "Email Address")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.eMail, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.VATRegNo, "VAT Reg: No")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.VATRegNo, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.DiscountPercent, "Discount Percent")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.DiscountPercent, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.DistributorPoint, "Distributor Point")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.DistributorPoint, new { @class = "required" })
                </div>
            </div>
            <div class="CustombuttonOnePart">
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Save" id="btnSave" />
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Update" id="btnUpdate" />
            </div>
            <div>
                <table id="tblCustomerInfo"></table>
                <div id="divCustomerInfoPager"></div>
            </div>
        </div>
    </div>  
    
    
    
}

Accounting/Views/POS_Setup/ExpenseInfo.cshtml
@model Repository.ExpenseInfo
@{
    ViewBag.Title = "ExpenseInfo";
}



@using (@Html.BeginForm())
{
    <div class="FormName">Expense Info</div>
    <div class="MainDiv">
        <div class="LeftPart">
            @Html.HiddenFor(m => m.ExpenseID)
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ExpenseCode, "Expense Code")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ExpenseCode, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ExpenseName, "Expense Name")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ExpenseName, new { @class = "required" })
                </div>
            </div>

            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.Remarks)
                </div>
                <div>
                    @Html.TextBoxFor(m => m.Remarks, new { @class = "required" })
                </div>
            </div>
            <div class="CustombuttonTwoParts">
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Save" id="btnSave" />
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Update" id="btnUpdate" />
            </div>
            <div>
                <table id="tblExpenseInfo"></table>
                <div id="divExpenseInfoPager"></div>
            </div>
        </div>
    </div>
}

Accounting/Views/POS_Setup/ProductCategory.cshtml
@model Repository.ProductCategory
@{
    ViewBag.Title = "ProductCategory";
}

<script src="~/Scripts/ApplicationJS/Pos_Setup/ProductCategory.js"></script>

@using (@Html.BeginForm())
{
    <div class="FormName">Product Category</div>
    <div class="MainDiv">
        <div class="LeftPart">
            @Html.HiddenFor(m => m.ProductCategoryID)
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ProductCategory1, "Product Category")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ProductCategory1, new { @class = "required" })
                </div>
            </div>

            <div class="CustombuttonOnePart">
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Save" id="btnSave" />
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Update" id="btnUpdate" />
            </div>

            <div>
                <table id="tblProductCategory"></table>
                <div id="ProductCategoryPager"></div>
            </div>
        </div>
    </div> 
}

Accounting/Views/POS_Setup/ProductInfo.cshtml
@model Repository.ProductInfo


@{
    ViewBag.Title = "ProductInfo";
}

<script src="~/Scripts/ApplicationJS/Pos_Setup/ProductInfo.js"></script>

@using (Html.BeginForm("UploadImage", "POS_Setup", FormMethod.Post,
    new
    {
        enctype = "multipart/form-data",
        id = "ImgForm",
        name = "ImgForm",
        target = "UploadTarget"
    }))
{
    <div class="FormName">Product Info</div>
    <div class="MainDiv">
        <div class="LeftPart">
            @Html.HiddenFor(m => m.ProductID)
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ProductCode, "Product Code ")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ProductCode, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ProductName, "Product Name")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ProductName, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ProductType, "Product Type")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ProductType, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ProductCategoryID, "Product Category")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.ProductCategoryID, (SelectList)ViewData["VdProductCategoryList"], "----Choose Category----")
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.BrandID, "Brand")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.BrandID, (SelectList)ViewData["VdBrandList"], "------Choose Brand------")
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ColorID, "Color")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.ColorID, (SelectList)ViewData["VdColorList"], "------Choose Color------")
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.SizeID, "Size")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.SizeID, (SelectList)ViewData["VdSizeList"], "------Choose Size------")
                </div>
            </div>

            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.TarrifTypeID, "Tarrif Type")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.TarrifTypeID, (SelectList)ViewData["VdTarrifTypeList"], "---Choose TarrifType---")
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.UnitID, "Unit")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.UnitID, (SelectList)ViewData["VdUnitList"], "--------Choose Unit--------")
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.UnitIDOut, "Unit ID Out")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.UnitIDOut, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ConversionRate, "Conversion Rate")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ConversionRate, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.VATTypeID, "VAT Type")
                </div>
                <div class="RightColumnDdl">
                    @Html.DropDownListFor(m => m.VATTypeID, (SelectList)ViewData["VdVAtList"], "-----Choose VatType----")
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.WeightPerUnit, "Weight Per Unit")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.WeightPerUnit, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.RatePerUnit, "Rate Per Unit")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.RatePerUnit, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.VATableRate, "VATable Rate")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.VATableRate, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.VATPercent, "VAT Percent")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.VATPercent, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.RebatePercent, "Re-Vat Percent")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.RebatePercent, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.SDPercent, "SD Percent")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.SDPercent, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.SupTaxPercent, "Sub Tax Percent")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.SupTaxPercent, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ApprovedPrice, "Approved Price")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ApprovedPrice, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ReorderLevel, "Reorder Level")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.ReorderLevel, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.Note, "Note")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.Note)
                </div>
            </div>

            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.EffectiveDate, "Effective Date")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.EffectiveDate, new { @class = "required" })
                </div>
            </div>
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.ProductImage, "Upload Image")
                </div>
                <div>
                    <input style="cursor: pointer;" type="file" name="file" id="file" />
                </div>
            </div>
            
            <div class="CustombuttonOnePart">
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" onclick="UploadImage()" type="submit" value="Save" id="btnSave" />
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Update" id="btnUpdate" />
            </div>
            <div>
                <table id="tblProductInfo"></table>
                <div id="ProductInfoPager"></div>
            </div>
        </div>
    </div>
}


<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js" type="text/javascript"></script>
<iframe id="UploadTarget" name="UploadTarget" onload="UploadImage_Complete();" style="position: absolute; left: -999em; top: -999em;"></iframe>
<div id="Images"></div>

Accounting/Views/POS_Setup/TarrifType.cshtml
@model Repository.TarrifType
@{
    ViewBag.Title = "TarrifType";
}



@using (@Html.BeginForm())
{
    <div class="FormName">Tarrif Type</div>
    <div class="MainDiv">
        <div class="LeftPart">
            @Html.HiddenFor(m => m.TarrifTypeID)
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.TarrifType1, "Tarrif Type")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.TarrifType1, new { @class = "required" })
                </div>
            </div>

            <div class="CustombuttonOnePart">
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Save" id="btnSave" />
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Update" id="btnUpdate" />
            </div>

            <div>
                <table id="tblTarrifType"></table>
                <div id="TarrifTypePager"></div>
            </div>
        </div>
    </div> 
}

Accounting/Views/POS_Setup/Unit.cshtml
@model Repository.Unit
@{
    ViewBag.Title = "Unit";
}


@using (@Html.BeginForm())
{
    <div class="FormName">Unit</div>
    <div class="MainDiv">
        <div class="LeftPart">
            @Html.HiddenFor(m => m.UnitID)
            <div class="LeftRow">
                <div class="LeftColumn">
                    @Html.LabelFor(m => m.UnitName, "Unit Name")
                </div>
                <div>
                    @Html.TextBoxFor(m => m.UnitName, new { @class = "required" })
                </div>
            </div>
            <div class="CustombuttonOnePart">
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Save" id="btnSave" />
                <input class="ac-inputs ui-button ui-widget ui-state-default ui-corner-all" type="button" value="Update" id="btnUpdate" />
            </div>
            <div>
                <table id="tblUnit"></table>
                <div id="UnitPager"></div>
            </div>
        </div>
    </div>
}